### ISSUE TITLE
Current Master-Release (2.1.2) not compatible with Symphony 2.6.X

### ISSUE THREAD

**Issue by twiro** [symphonycms/export_ensemble#22]
The current master release 2.1.2 _(that is officially bundled with Symphony)_ does not include/support the **vendor**-folder that has been introduced in Symphony 2.6.0.

The integration branch of this extension includes a** [PR](https://github.com/symphonycms/export_ensemble/pull/21)** that fixes this problem, but hasn't found its way to an official release - so Symphony _(Bundle)_ 2.6.0 up to 2.6.4 are shipping an incompatible version of this extension.

Would be awesome if this could be fixed for the upcoming Symphony 2.6.5 is release.

Maybe a version 2.1.3 that is marked as only compatible up to Symphony 2.5.X and another _(2.2.0 ?)_ release that is marked as compatible with 2.6.X and upwards would be a good solution?

@brendo @nitriques - could you have a look? Thanks alot!

**Comment by nitriques** [comment]
@twiro Thanks for reporting. We also found that there's a bug on getsymphony.com which would fetch the zip directly from github instead of the version we are uploading... @brendo did you had the chance to look at it ? If not, I'll try to fix it ASAP.

@twiro We will also release 2.6.5 that will hopefully deal with all the troubles I had with my first release :P

**Comment by nitriques** [comment]
[There you go !](https://github.com/symphonycms/export_ensemble/releases/tag/2.2.0)
